# -*- coding: utf-8 -*-
"""Tugas perkondisian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aK9Fv3o-dUgK7r4bv9XtpQl3XlpEDKbs
"""

# Fungsi untuk menentukan kelulusan siswa
def cek_kelulusan(nama, nilai):
    if nilai >= 60:
        return f"{nama} dinyatakan LULUS dengan nilai {nilai}."
    else:
        return f"{nama} dinyatakan TIDAK LULUS dengan nilai {nilai}."

# Fungsi untuk menampilkan menu
def show_menu():
    print("\n--- Program Penentuan Kelulusan ---")
    print("[1] Masukkan Data Siswa")
    print("[2] Keluar")

# Fungsi untuk memulai program
def main_program():
    while True:
        show_menu()
        pilihan = int(input("Pilih menu: "))

        if pilihan == 1:
            nama = input("Masukkan Nama Siswa: ")
            nilai = int(input("Masukkan Nilai Siswa: "))
            hasil = cek_kelulusan(nama, nilai)
            print(hasil)
        elif pilihan == 2:
            print("Terima kasih!")
            break
        else:
            print("Pilihan tidak valid. Coba lagi.")

# Memulai program
if __name__ == "__main__":
    main_program()