# -*- coding: utf-8 -*-
"""Praktikum 04_Perkondisian.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwLQDhVSpf8wk42BiSNcd-QXf1QNkSTq
"""

a = 33
b = 100
if (a>b):
    print("Nilai A lebih Besar dari B")

a = 33
b = 100
if (a>b):
    print("Nilai A lebih Besar dari B")
else:
    print("Nilai A lebih Kecil dari B")

a = 100
b = 50
if (a>b):
    print("Nilai A lebih Besar dari B")
else:
    print("Nilai A lebih Kecil dari B")

a = 100
b = 50
if (a>b):
    print("Nilai A lebih Besar dari B")
elif (a<b):
    print("Nilai A lebih Kecil dari B")
else:
    print("Nilai A Sama Dengan B")

if (a>b) : print("A lebih Besar dari B")

a = 10
b = 5

print("A lebih Besar dari B") if a>b else print("A lebih Kecil dari B")

print("A lebih Besar dari B") if a>b else print("A lebih Kecil dari B") if a<b else print("A sama dengan B")

bilangan = 25

if (bilangan %2 ==0):
    print("Bilangan Genap")
else:
    print("Bilangan Ganjil")

nama = input ("Masukkan Nama Anda : ")
print ("Nama Anda Adalah : " + nama)

bilangan = int (input("Masukkan Bilangan : "))

if (bilangan %2 == 0):
    print(bilangan, "Adalah Bilangan Genap")
else:
    print(bilangan, "Adalah Bilangan Ganjil")