# -*- coding: utf-8 -*-
"""Praktikum 4_Perkondisian.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a40hpryWvfn99oQ_MBki5-dsTdMCJNOw
"""

def nama_fungsi():
    print ("Hello ini Fungsi")

# Membuat Fungsi
def salam():
    print ("Hello, Selamat Pagi")

## Pemanggilan Fungsi
salam()

# Membuat Fungsi
def salam():
    print ("Hello, Selamat Pagi")

## Pemanggilan Fungsi
salam()
salam()
salam()

def salam(ucapan):
    print(ucapan)

def fungsi(parameter):
    print(parameter)

# Membuat fungsi dengan parameter
def luas_segitiga(alas, tinggi):
    luas = (alas * tinggi) / 2
    print("Luas segitiga: %f" % luas)

# Pemanggilan fungsi
luas_segitiga(4, 6)

def luas_persegi(sisi):
    luas = sisi * sisi
    return luas

# pemanggilan fungsi
print ("Luas persegi: %d" % luas_persegi(6))

# rumus: sisi x sisi
def luas_persegi(sisi):
    luas = sisi * sisi
    return luas


# rumus: sisi x sisi x sisi
def volume_persegi(sisi):
    volume = luas_persegi(sisi) * sisi

# membuat variabel global
nama = "Muhammad Lutfi Kurniawan"
versi = "1.0.0"

def help():
    # ini variabel lokal
    nama = "Programku"
    versi = "1.0.2"
    # mengakses variabel lokal
    print("Nama: %s" % nama)
    print("Versi: %s" % versi)

# mengakses variabel global
print("Nama: %s" % nama)
print("Versi: %s" % versi)

# memanggil fungsi help()
help()

# Variabel global untuk menyimpan data Buku
buku = []

# fungsi untuk menampilkan semua data
def show_data():
    if len(buku) <= 0:
        print("BELUM ADA DATA")
    else:
        for indeks in range(len(buku)):
            print("[%d] %s" % (indeks, buku[indeks]))

# fungsi untuk menambah data
def insert_data():
    buku_baru = raw_input("Judul Buku: ")
    buku.append(buku_baru)

# fungsi untuk edit data
def edit_data():
    show_data()
    try:
        indeks = int(input("Inputkan ID buku: "))  # konversi ke integer
        if indeks >= len(buku):
            print("ID salah")
        else:
            judul_baru = input("Judul baru: ")  # gunakan input() di Python 3
            buku[indeks] = judul_baru
    except ValueError:
        print("Input harus berupa angka")

# fungsi untuk menghapus data
def delete_data():
    show_data()
    try:
        indeks = int(input("Inputkan ID buku: "))  # konversi ke integer
        if indeks >= len(buku):
            print("ID salah")
        else:
            buku.remove(buku[indeks])
    except ValueError:
        print("Input harus berupa angka")

# Variabel global untuk menyimpan data Buku
buku = []

# fungsi untuk menampilkan semua data
def show_data():
    if len(buku) <= 0:
        print("BELUM ADA DATA")
    else:
        for indeks in range(len(buku)):
            print("[%d] %s" % (indeks, buku[indeks]))

# fungsi untuk menambah data
def insert_data():
    buku_baru = input("Judul Buku: ")  # ganti raw_input() dengan input()
    buku.append(buku_baru)

# fungsi untuk edit data
def edit_data():
    show_data()
    try:
        indeks = int(input("Inputkan ID buku: "))  # konversi ke integer
        if indeks >= len(buku):
            print("ID salah")
        else:
            judul_baru = input("Judul baru: ")  # ganti raw_input() dengan input()
            buku[indeks] = judul_baru
    except ValueError:
        print("Input harus berupa angka!")

# fungsi untuk menghapus data
def delete_data():
    show_data()
    try:
        indeks = int(input("Inputkan ID buku: "))  # konversi ke integer
        if indeks >= len(buku):
            print("ID salah")
        else:
            buku.remove(buku[indeks])
    except ValueError:
        print("Input harus berupa angka!")

# fungsi untuk menampilkan menu
def show_menu():
    print("\n")
    print("----------- MENU ----------")
    print("[1] Show Data")
    print("[2] Insert Data")
    print("[3] Edit Data")
    print("[4] Delete Data")
    print("[5] Exit")

    try:
        menu = int(input("PILIH MENU> "))  # konversi ke integer
        print("\n")

        if menu == 1:
            show_data()
        elif menu == 2:
            insert_data()
        elif menu == 3:
            edit_data()
        elif menu == 4:
            delete_data()
        elif menu == 5:
            exit()
        else:
            print("Salah pilih!")
    except ValueError:
        print("Input harus berupa angka!")

if __name__ == "__main__":
    while(True):
        show_menu()